config/routes.rb
Rails.application.routes.draw do
  get 'web/home' => redirect('/')

  get 'about-us' => 'web#about_us', as: 'web_about_us'

  post 'web/search'

  root to: 'web#home'

  resources :books, except: [:new, :create]
  resources :authors do
    resources :books
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :reviews, as: :reviewable
  has_many :books
  validates :email, :first_name, presence: true

  before_save :clean_name

  REDIRECTED_AUTHORS = { '124' => 7, '25' => 2 }

  def to_s
    "#{first_name} #{last_name}".strip
  end

  private

  def clean_name
    self.first_name = first_name.titleize
    self.last_name = last_name.to_s.titleize
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews, as: :reviewable
  belongs_to :author, optional: true, counter_cache: true, touch: true
  validates :author, presence: { if: :new_data? }

  before_create :update_author_name

  scope :with_title, -> { where.not(title: nil) }
  scope :newer_than, ->(year) { where('year >= ?', year) }

  delegate :first_name, to: :author, prefix: true
  delegate :created_at, to: :author, prefix: true

  attr_accessor :price

  BOOK_VAT = 10

  def price_with_vat
    return if price.nil?
    price * (100 + BOOK_VAT) / 100
  end

  def reviews_count
    reviews.count
  end

  private

  def new_data?
    created_at.nil? || created_at > Date.new(2016, 11, 22)
  end

  def update_author_name
    self.author_name = author.to_s
  end
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence: true
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_variant
  before_action :set_locale
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  private

  def render_404
    render 'web/404', status: 404
  end

  def set_variant
    request.variant = :phone if browser.device.mobile?
  end

  def set_locale
    I18n.locale = params[:locale] if params[:locale]
    @country = Country.find_by!(code: I18n.locale)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :redirected_authors, only: :show
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.order(params_order_to_db)
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def redirected_authors
    return unless params[:id].in? Author::REDIRECTED_AUTHORS.keys
    redirect_to author_path(Author::REDIRECTED_AUTHORS[params[:id]])
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:first_name, :last_name, :email, :phone, :city, :address, :website)
    end

    def params_order_to_db
      {
        name: :first_name,
        created_at: 'created_at DESC'
        }[params[:order]] || :email
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @author = Author.find(params[:author_id])
    @books = Book.where(author_id: params[:author_id])
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @author = Author.find(params[:author_id])
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.author_id = params[:author_id]

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author_id, :description, :year, :available, :section, :shelf, :order)
    end
end

app/controllers/web_controller.rb
class WebController < ApplicationController
  def home
  end

  def about_us
  end

  def search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.haml
= form_for @author do |f|
  - if @author.errors.any?
    #error_explanation
      %h2= "#{pluralize(@author.errors.count, "error")} prohibited this author from being saved:"
      %ul
        - @author.errors.full_messages.each do |msg|
          %li= msg

  - %i(first_name last_name email phone city address website).each do |field|
    = render 'common/field_text', f: f, field: field
  .actions
    = f.submit 'Save'

app/views/authors/edit.html.haml
%h1 Editing author

= render 'form'

= link_to 'Show', @author
\|
= link_to 'Back', authors_path

app/views/authors/index.html.haml
- content_for :title do
  Authors
- content_for :presearch do
  %p Tip: Search by author's name

%h1 Listing authors

%table
  %thead
    %tr
      %th First name
      %th Last name
      %th Email
      %th Phone
      %th City
      %th Address
      %th Website
      %th
      %th
      %th

  %tbody
    - @authors.each do |author|
      %tr
        %td= author.first_name
        %td= author.last_name
        %td= author.email
        %td= author.phone
        %td= author.city
        %td= author.address
        %td= author.website
        %td= link_to 'Show', author
        %td= link_to 'Edit', edit_author_path(author)
        %td= link_to 'Destroy', author, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Author', new_author_path

app/views/authors/new.html.haml
%h1 New author

= render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.haml
= @author.decorate.title

%p#notice= notice

%p
  %b First name:
  = @author.first_name
%p
  %b Last name:
  = @author.last_name
%p
  %b Email:
  = @author.email
%p
  %b Phone:
  = @author.phone
%p
  %b City:
  = @author.city
%p
  %b Address:
  = @author.address
%p
  %b Website:
  = @author.website

%p= link_to 'See books!', author_books_path(@author)

= link_to 'Edit', edit_author_path(@author)
\|
= link_to 'Back', authors_path

app/views/books/_form.html.haml
= form_for [@author, @book] do |f|
  - if @book.errors.any?
    #error_explanation
      %h2= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg

  = render 'common/field_text', f: f, field: :title
  = render 'common/field_text', f: f, field: :description
  .field
    = f.label :year
    = f.number_field :year
  .field
    = f.label :available
    = f.check_box :available
  = render 'common/field_text', f: f, field: :section
  .field
    = f.label :shelf
    = f.number_field :shelf
  .field
    = f.label :order
    = f.number_field :order
  .actions
    = f.submit 'Save'

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @book
\|
= link_to 'Back', books_path

app/views/books/index.html.haml
%h1 Listing books

%table
  %thead
    %tr
      %th Title
      %th Author
      %th Description
      %th Year
      %th Available
      %th Section
      %th Shelf
      %th Order
      %th
      %th
      %th

  %tbody
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.author
        %td= book.description
        %td= book.year
        %td= book.available
        %td= book.section
        %td= book.shelf
        %td= book.order
        %td= link_to 'Show', book
        %td= link_to 'Edit', edit_book_path(book)
        %td= link_to 'Destroy', book, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Book', new_author_book_path(@author)

app/views/books/new.html.haml
%h1 New book

= render 'form'

= link_to 'Back', books_path

app/views/books/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @book.title
%p
  %b Author:
  = link_to @book.author, author_path(@book.author_id)
%p
  %b Description:
  = @book.description
%p
  %b Year:
  = @book.year
%p
  %b Available:
  = @book.available
%p
  %b Section:
  = @book.section
%p
  %b Shelf:
  = @book.shelf
%p
  %b Order:
  = @book.order

= link_to 'Edit', edit_book_path(@book)
\|
= link_to 'Back', books_path

app/views/common/_field_text.html.haml
.field
  = f.label field
  = f.text_field field

app/views/layouts/_common_layout.html.haml
= yield(:presearch)
%p
  = form_tag web_search_path do
    = text_field_tag :text_to_search
    = submit_tag 'Search'
= yield

%p
  Locale: #{I18n.locale}
  = I18n.localize Time.current, format: :shorter
- console if Rails.env.development?

app/views/layouts/application.es_ES.html.haml
!!!
%html
  %head
    %title
      = yield(:title)
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %h1
      = I18n.t 'welcome'
    = render 'layouts/common_layout'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = yield(:title)
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %ul
      %li= link_to 'Authors', authors_path
      %li= link_to 'Books', books_path
      %li= link_to 'Home', web_home_path
      %li= link_to 'About us', web_about_us_path
      %li= link_to 'Root', root_path
    = yield(:presearch)
    %p
      = form_tag web_search_path do
        = text_field_tag :text_to_search
        = submit_tag 'Search'
    = yield

    %p
      Locale: #{I18n.locale}
      = I18n.localize Time.current, format: :long
    - console if Rails.env.development?

app/views/web/404.html.haml
%h1
  404 - Not Found

app/views/web/about_us.html.haml
%h1 Web#about_us
%p Find me in app/views/web/about_us.html.haml

app/views/web/home.html+phone.haml
%h1 Hey! I'm mobile!!

app/views/web/home.html.haml
- content_for :title do
  Library - Your best pet project

%h1 Still desktop... :-(
Variant actual: #{request.user_agent}

app/views/web/search.html.haml
%h1 Web#search
%p Searching for #{params[:text_to_search]}